### ISSUE TITLE
Instability in the watch test: Windows

### ISSUE THREAD

**Issue by promiseofcake** [vsco/dcdr#68]
Reported via @fruch in #65 

> there is some instability in the watch test (in windows it's failing constently)

We are not testing for Windows, an improvement would be to address that.

**Comment by fruch** [comment]
I have a bunch of fixes for windows I'll put them into a PR, 
anyhow the instability  I was refering too, was that it failed in the travis CI:
https://travis-ci.org/vsco/dcdr/builds/352241579?utm_source=github_status&utm_medium=notification

**Comment by fruch** [comment]
I think I've pined down the issue.

There two call to watch, one on New and one on Watch. there a lock on c.watcher.New() and also on c.watcher.Watch().

I'm a total newbie on golang, but seem like a race condition that makes the test pass on linux (and because fsnotify works different on windows, it's get stuck always, and the bug in the test is surfaced)

**Comment by fruch** [comment]
I think this change is the cause:
https://github.com/vsco/dcdr/commit/d8d6f27dc2830debbe78fcb09c4b67fe8c5219d4

**Comment by fruch** [comment]
I'm quite sure it's not windows only this issue, seen it fail on CI on #71 (rerun magicly solved it)
